import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, "..");

const DEFAULT_SITE_URL = "https://pvblocordero.com";
const siteUrl = (process.env.SITE_URL || DEFAULT_SITE_URL).replace(/\/+$/, "");

const staticRoutes = [
  { path: "/home", changefreq: "weekly", priority: "1.0" },
  { path: "/about", changefreq: "monthly", priority: "0.8" },
  { path: "/skills", changefreq: "monthly", priority: "0.8" },
  { path: "/art", changefreq: "weekly", priority: "0.8" },
  { path: "/resume", changefreq: "monthly", priority: "0.7" },
];

const featuredProjects = new Set([
  "numeneon",
  "numeneon-light",
  "pneuma",
  "transcendence",
]);

const xmlEscape = (value) =>
  value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&apos;");

async function getProjectRoutes() {
  const projectsDir = path.join(ROOT_DIR, "projects");
  const files = await readdir(projectsDir, { withFileTypes: true });

  return files
    .filter((entry) => entry.isFile() && entry.name.endsWith(".html"))
    .map((entry) => entry.name.replace(/\.html$/, ""))
    .sort((a, b) => a.localeCompare(b))
    .map((slug) => ({
      path: `/projects/${slug}`,
      changefreq: "monthly",
      priority: featuredProjects.has(slug) ? "0.7" : "0.6",
    }));
}

function buildSitemapXml(routes) {
  const body = routes
    .map(
      (route) => `  <url>\n    <loc>${xmlEscape(`${siteUrl}${route.path}`)}</loc>\n    <changefreq>${route.changefreq}</changefreq>\n    <priority>${route.priority}</priority>\n  </url>`,
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
}

function buildRobotsTxt() {
  return `# robots.txt for pablopistola\n# Auto-generated by scripts/generate-sitemap.js\n\nUser-agent: *\nAllow: /\n\n# Exclude technical/build paths if they become publicly reachable\nDisallow: /dist/\nDisallow: /node_modules/\n\nSitemap: ${siteUrl}/sitemap.xml\n`;
}

async function main() {
  const projectRoutes = await getProjectRoutes();
  const routes = [...staticRoutes, ...projectRoutes];

  await writeFile(path.join(ROOT_DIR, "sitemap.xml"), buildSitemapXml(routes), "utf8");
  await writeFile(path.join(ROOT_DIR, "robots.txt"), buildRobotsTxt(), "utf8");

  console.log(`Generated sitemap.xml (${routes.length} URLs) and robots.txt for ${siteUrl}`);
}

main().catch((error) => {
  console.error("Failed to generate sitemap/robots:", error);
  process.exitCode = 1;
});
